# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable:     true
            timestampable: true
            tree:          true

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Isics\Bundle\OpenMiamMiamUserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: open_miam_miam_user_registration
    profile:
        form:
            type: open_miam_miam_user_profile
    from_email:
        address:     %mailer_sender_address%
        sender_name: %mailer_sender_name%
    service:
        mailer: fos_user.mailer.twig_swift

# LiipImagineBundle Configuration
liip_imagine:
    filter_sets:
        s:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        m:
            filters:
                thumbnail: { size: [200, 150], mode: outbound }
        l:
            filters:
                thumbnail: { size: [400, 300], mode: outbound }

# StfalconTinymceBundle
stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    theme:
        simple:
            theme:     "modern"
            menubar:   false
            statusbar: false
            plugins:
                - "autolink lists textcolor"
            toolbar1: "bold,italic,underline,forecolor,styleselect,bullist,numlist,undo,redo,removeformat"
            style_formats:
                - { title: "Titre", block: "h2" }
                - { title: "Sous-titre", block: "h3" }
                - { title: "Paragraphe", block: "p" }

# Services
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [IsicsOpenMiamMiamBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node:       %node_path%
            node_paths: [%node_path%, %node_modules_path%]
            apply_to:   "\.less$"
        uglifycss:
            bin: %node_uglifycss_bin%
        uglifyjs2:
            bin: %node_uglifyjs_bin%
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
