resources:
    Isics\Bundle\OpenMiamMiamBundle\Entity\Branch:
        itemOperations:
            special:
                normalization_context:
                    groups: ['categories']
                method: 'GET'
                path: '/branch/{id}/categories'
                requirements:
                    id: '\d+'
                controller: 'Isics\Bundle\OpenMiamMiamBundle\Controller\Api\BranchSpecial'
