resources:
    Isics\Bundle\OpenMiamMiamBundle\Entity\Branch:
        itemOperations:
            special:
                method: 'GET'
                path: '/branch/{id}/categories'
                requirements:
                    id: '\d+'
                controller: 'Isics\Bundle\OpenMiamMiamBundle\Controller\BranchSpecial'
