resources:
    Isics\Bundle\OpenMiamMiamBundle\Entity\Category:
        properties:
            children:
                subresource:
                    resourceClass: 'Isics\Bundle\OpenMiamMiamBundle\Entity\Category'
                    collection: true
        itemOperations: 
            get:
                method: 'GET' #étrangement obligatoire pour que /api/categories/{id}/childrens fonctionne...
                # probablement a cause de : Note: By default, API Platform uses the first GET operation defined in itemOperations to generate the IRI of an item and the first GET operation defined in collectionOperations to generate the IRI of a collection.
        collectionOperations:
            api_categories_childrens_get_subresource:
                swagger_context:
                    summary: Test
                method: 'GET'
                route_name: 'api_categories_childrens_get_subresource'
                normalization_context:
                    groups: ['category_children']
    Isics\Bundle\OpenMiamMiamBundle\Entity\SalesOrder:
        itemOperations: 
            place_order:
                method: 'POST'
                path: '/sales_orders'
                normalization_context:
                    groups: ['order_result']
                controller: 'Isics\Bundle\OpenMiamMiamBundle\Controller\Api\SalesOrder\PostOrder'
                defaults:
                    _api_receive: false
    Isics\Bundle\OpenMiamMiamBundle\Entity\Producer:
        itemOperations: 
            get:
                method: 'GET'
                normalization_context:
                    groups: ['producer']
    Isics\Bundle\OpenMiamMiamBundle\Entity\Product:
        itemOperations: 
            get:
                method: 'GET'
                normalization_context:
                    groups: ['product']
    Isics\Bundle\OpenMiamMiamBundle\Entity\Branch:
        #properties:
        #    name:
        itemOperations:
            infos:
                method: 'GET'
                path: '/branch/{id}/infos'
                normalization_context:
                    groups: ['branch_infos']
            occurences:
                method: 'GET'
                path: '/branch/{id}/occurences'
                normalization_context:
                    groups: ['occurences']
                controller: 'Isics\Bundle\OpenMiamMiamBundle\Controller\Api\BranchOccurences'
            special:
                normalization_context:
                    groups: ['categories']
                method: 'GET'
                path: '/branch/{id}/categories'
                requirements:
                    id: '\d+'
                controller: 'Isics\Bundle\OpenMiamMiamBundle\Controller\Api\BranchCategories'
            products:
                normalization_context:
                    groups: ['branch_categories_products']
                method: 'GET'
                path: '/branch/{id}/categories/{idCat}/products'
                requirements:
                    id: '\d+'
                    idCat: '\d+'
                swagger_context:
                    summary: Récupère la liste des sous-catégories et des produits
                    requestBody: '{"id": 1, "idCat":2}'
                    parameters:
                        -
                            name: id
                            in: path
                            required: true
                            type: integer
                        -
                            name: idCat
                            in: path
                            required: true
                            type: integer
                    responses:
                        200:
                            description: "les sous catégories avec leur produits"
                        404:
                            description: "Resource not found"
                controller: 'Isics\Bundle\OpenMiamMiamBundle\Controller\Api\BranchCategoryProducts'
        collectionOperations: 
            get:
                method: 'GET'
        